{
  "$schema": "http://json-schema.org",
  "title": "PycnogonidStateMatrix",
  "description": "Schema for validating the pycnogonid parasite behavioral state machine, environmental thresholds, and physical constants.",
  "type": "object",
  "required": [
    "agent_id",
    "current_state",
    "physical_properties",
    "environmental_context",
    "state_transitions"
  ],
  "properties": {
    "agent_id": {
      "type": "string",
      "description": "Unique identifier for the specific pycnogonid instance."
    },
    "current_state": {
      "type": "string",
      "enum": [
        "FREE_SWIMMING",
        "HOST_SEEKING",
        "ENCYSTED_FEEDING",
        "INTERNAL_FREE_MOVING",
        "FREE_LIVING_ADULT",
        "DEAD"
      ],
      "description": "The active behavioral state (S_t) of the agent."
    },
    "physical_properties": {
      "type": "object",
      "required": [
        "leg_span_mm",
        "proboscis_length_mm",
        "leg_ratio_r",
        "surface_area_mm2",
        "mass_mg",
        "thrust_force_f"
      ],
      "properties": {
        "leg_span_mm": { "type": "number", "minimum": 0.0 },
        "proboscis_length_mm": { "type": "number", "minimum": 0.0 },
        "leg_ratio_r": { 
          "type": "number", 
          "description": "L_femur divided by combined L_tibia segments." 
        },
        "surface_area_mm2": { "type": "number", "minimum": 0.0 },
        "mass_mg": { "type": "number", "minimum": 0.0 },
        "thrust_force_f": { "type": "number", "description": "Thrust force generated by leg beats." }
      }
    },
    "environmental_context": {
      "type": "object",
      "required": [
        "fluid_viscosity_pas",
        "chemical_gradient_delta_c",
        "habitat_suitability_hsi"
      ],
      "properties": {
        "fluid_viscosity_pas": { 
          "type": "number", 
          "description": "Dynamic fluid viscosity (mu) in Pascal-seconds (e.g., 0.00108 for seawater)." 
        },
        "chemical_gradient_delta_c": { 
          "type": "number", 
          "description": "Strength of the host chemical emission gradient." 
        },
        "habitat_suitability_hsi": { 
          "type": "number", 
          "minimum": 0.0, 
          "maximum": 1.0, 
          "description": "Calculated geometric mean of environmental fitness." 
        }
      }
    },
    "state_transitions": {
      "type": "array",
      "description": "The logic matrix defining how the agent evaluates state shifts.",
      "items": {
        "type": "object",
        "required": [
          "from_state",
          "to_state",
          "trigger_condition",
          "physics_modifier_update"
        ],
        "properties": {
          "from_state": {
            "type": "string",
            "enum": ["FREE_SWIMMING", "HOST_SEEKING", "ENCYSTED_FEEDING", "INTERNAL_FREE_MOVING", "FREE_LIVING_ADULT"]
          },
          "to_state": {
            "type": "string",
            "enum": ["FREE_SWIMMING", "HOST_SEEKING", "ENCYSTED_FEEDING", "INTERNAL_FREE_MOVING", "FREE_LIVING_ADULT", "DEAD"]
          },
          "trigger_condition": {
            "type": "object",
            "required": ["variable", "operator", "threshold"],
            "properties": {
              "variable": { 
                "type": "string", 
                "enum": ["chemical_gradient_delta_c", "time_elapsed", "w_host", "p_penetrate", "length_t", "hsi", "infection_intensity_i"] 
              },
              "operator": { "type": "string", "enum": [">", "<", ">=", "<=", "==", "->0"] },
              "threshold": { "type": "number" }
            }
          },
          "physics_modifier_update": {
            "type": "object",
            "required": ["flow_regime_exponent_n"],
            "properties": {
              "flow_regime_exponent_n": { 
                "type": "number", 
                "enum": [0.5, 1.0],
                "description": "Changes velocity equations. 0.5 for turbulent/open-water, 1.0 for highly viscous intrabody flow." 
              }
            }
          }
        }
      }
    }
  }
}
